### ISSUE TITLE
Venganza 😈

### ISSUE THREAD

**Issue by ByEvidencias** [Indexa2/StaticFluids---IndexDev#1]
Esos fluidos están más estáticos que tu pene al ver a una 019

**Comment by Indexa2** [comment]
Mi querido "ByEvidencias", tu comentario me la suda completamente, aparte de que tienes nombre, de persona psicopata y hacker, ademas de eso eres un puto macaco, que seguramente esta ahora en llamada, con un puto mexicano de mierda, ah no espera, que soy yo xdxdxd lololol wtf xdxdxd ekisde

**Comment by ByEvidencias** [comment]
Apoco si mi querido IndexACM

**Comment by Indexa2** [comment]
Ademas mi querido "ByEvidencias" yo en mi codigo, no uso "$this->plugin = $plugin" no compares eso, con cachear correctamente los events

Att: IndexDev <3

**Comment by ByEvidencias** [comment]
Puro singletontrait hermanito, yo no veo ningún $this-plugin, aparte que tú código es más corto que el pene de cevin

**Comment by Indexa2** [comment]
Hermanito, tengo capturas que puedo facilmente subir, por este mismo medio, dando asi tu derrota de mierda.

**Comment by ByEvidencias** [comment]
Apoco si mi quedo RepoDEX

**Comment by Indexa2** [comment]
No confundas cambiar tu codigo de mierda, por que usas "$this->plugin = $plugin" y usar singletontrait solo por que un experto como HVNS, te dijo que usaras.

**Comment by ByEvidencias** [comment]
Son commits Bro 😳, ni q puedas actualizar el tuyo pq es más corto q el prime de ansu fati

**Comment by Indexa2** [comment]
Tus plugins para lo unico que sirven, son para rascarme el culo, el codigo que utilizas en tus plugins, es mas facil que follar con Cevin.

**Comment by ByEvidencias** [comment]
Pero si tú código de 16 líneas daba error y hvns te tuvo q ayudar
